version: '3.8'

services:
  # Aplicação principal
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=http://supabase:54321
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q
      - REDIS_URL=redis://redis:6379
    depends_on:
      - supabase
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Supabase local
  supabase:
    image: supabase/supabase-dev
    ports:
      - "54321:54321"  # API
      - "54322:54322"  # Auth
      - "54323:54323"  # Dashboard
      - "5432:5432"    # PostgreSQL
    environment:
      # Secrets (CRÍTICOS - devem ser iguais aos do Easypanel)
      - POSTGRES_PASSWORD=nagent-supabase-pg-secure-2024-xyz789-abc123-def456
      - JWT_SECRET=nagent-jwt-secret-2024-xyz789-abc123-def456-ghi789
      - SECRET_KEY_BASE=nagent-secret-key-base-2024-xyz789-abc123-def456-ghi789-jkl012-mno345-pqr678
      - VAULT_ENC_KEY=nagent-vault-enc-key-32-chars
      - ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
      - SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q
      - DASHBOARD_USERNAME=supabase
      - DASHBOARD_PASSWORD=nagent-dashboard-secure-2024-xyz789
      # Database
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      # Supervisor
      - POOLER_PROXY_PORT_TRANSACTION=6543
      - POOLER_DEFAULT_POOL_SIZE=20
      - POOLER_MAX_CLIENT_CONN=100
      - POOLER_TENANT_ID=nagent-tenant-2024
      # API Proxy
      - KONG_HTTP_PORT=8000
      - KONG_HTTPS_PORT=8443
      # API
      - PGRST_DB_SCHEMAS=public,storage,graphql_public
      # Auth
      - SITE_URL=https://ncagent.ness.tec.br
      - ADDITIONAL_REDIRECT_URLS=
      - JWT_EXPIRY=3600
      - DISABLE_SIGNUP=false
      - API_EXTERNAL_URL=https://ncagent.ness.tec.br/api
      # Email Auth
      - ENABLE_EMAIL_SIGNUP=true
      - ENABLE_EMAIL_AUTOCONFIRM=true
      - SMTP_ADMIN_EMAIL=resper@ness.com.br
      - SMTP_HOST=localhost
      - SMTP_PORT=587
      - SMTP_USER=resper@ness.com.br
      - SMTP_PASS=nagent-smtp-password-2024
      - SMTP_SENDER_NAME=n.CISO Platform
      - ENABLE_ANONYMOUS_USERS=false
      # Phone Auth
      - ENABLE_PHONE_SIGNUP=true
      - ENABLE_PHONE_AUTOCONFIRM=true
      # Studio
      - STUDIO_DEFAULT_ORGANIZATION=Default Organization
      - STUDIO_DEFAULT_PROJECT=Default Project
      - STUDIO_PORT=3000
      - SUPABASE_PUBLIC_URL=https://ncagent.ness.tec.br
      # Functions
      - FUNCTIONS_VERIFY_JWT=false
      # Logs
      - LOGFLARE_LOGGER_BACKEND_API_KEY=nagent-logflare-backend-2024-xyz789-abc123-def456
      - LOGFLARE_API_KEY=nagent-logflare-api-2024-xyz789-abc123-def456
      - DOCKER_SOCKET_LOCATION=/var/run/docker.sock
      - GOOGLE_PROJECT_ID=GOOGLE_PROJECT_ID
      - GOOGLE_PROJECT_NUMBER=GOOGLE_PROJECT_NUMBER
    volumes:
      - supabase_data:/var/lib/postgresql/data

  # Redis para cache e filas
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Worker para processamento de documentos
  worker:
    build: .
    command: node apps/worker/dist/index.js
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - NEXT_PUBLIC_SUPABASE_URL=http://supabase:54321
      - SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q
    depends_on:
      - redis
      - supabase

volumes:
  supabase_data:
  redis_data:
